💄Tooltip show automatically
SSWConsulting/SSW.Rules pull request #1001
Opened 2023-05-31 03:26 UTC by Aibono1225

Fixes #1000 

Changes I made:
- Make the "RulesGPT" tooltip appear automatically after 3s, and disappear after 15s.
- Tooltip - Change text to “✨ Try out RulesGPT”
- New rule button - Change to “Create a SSW Rule”

![D846D27E-0AE8-4BE9-9EA1-71C3AC17DEBD](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/5958e414-c65e-441f-b0fe-f2446a89d118)

2023-05-31 03:47 UTC, bradystroud requested changes

2023-05-31 03:47 UTC, bradystroud commented on src/components/header/header.js
> +            <Tooltip text="Create a SSW Rule">
```suggestion
            <Tooltip text="Create an SSW Rule">
```

2023-05-31 03:47 UTC, bradystroud commented on src/components/tooltip/tooltip.js
Great job on the Tooltip! 👏 Here are a couple of quick ideas:

	1.	Adding delay props: How about we add showDelay and hideDelay as props? 🔄 It’d give us more wiggle room and we can say bye-bye to the text checking. 👋
	2.	location.pathname bit: It’s kinda just chilling in there but we’re not using it. 🤷‍♂️ Might be good to take it out to keep things clean and tidy. 🧹

Overall, fantastic work, keep it up! 🚀

2023-05-31 05:20 UTC, Aibono1225 commented on src/components/tooltip/tooltip.js
All Done ⭐
Added showDelay and hideDelay props.
And removed location.pathname

2023-06-01 01:36 UTC, bradystroud approved these changes
lgtm 🚀

2023-06-01 01:36 UTC, merged