♻️ Handle empty title in Acknowledgements
SSWConsulting/SSW.Rules pull request #1009
Opened 2023-06-07 10:32 UTC by Aibono1225

Fixes #1008 

Changes I made:
- Rewrite function to handle Acknowledgements images better
- Log a warning when there is no title on the image

![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/6dd40e72-71c7-4f8e-9fd4-8f6fe1a9ef8a)

2023-06-07 21:44 UTC, bradystroud requested changes

2023-06-07 21:44 UTC, bradystroud commented on src/components/acknowledgements/acknowledgements.js
> +      console.warn('Warning: Title is missing.');
Instead of logging this, can we add an app insights log?

Let me know if you need help with this 🙂

2023-06-08 10:00 UTC, Aibono1225 commented
Hi @bradystroud ,

Now the warning log can show in the Application Insights 😊
![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/a57141ef-30c4-41ca-bd05-c680edff713d)

2023-06-09 01:35 UTC, bradystroud approved these changes
💪🚀 LGTM

2023-06-09 05:05 UTC, bradystroud approved these changes

2023-06-09 05:05 UTC, merged