✨Add User Rules Page
SSWConsulting/SSW.Rules pull request #1075
Opened 2023-08-22 05:32 UTC by Aibono1225

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1046

Changes:
- Added a user rules page to display a user's rule data fetched from the Github API
- Added pagination at the bottom of the list of rules

![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/ae1ee60a-44b3-4004-9f79-db5a681bd16a)

**Figure: the new page**

2023-08-23 22:14 UTC, bradystroud requested changes
Looking good 😊

2023-08-24 03:34 UTC, Aibono1225 commented on src/pages/user-rules.js
> +                    : 'bg-ssw-grey text-text-gray-400'
oops it's a mistake 😣

2023-08-24 03:36 UTC, Aibono1225 commented on src/pages/user-rules.js
> +    const githubRepo = 'SSW.Rules.Content';
We didn't have these variables in .env.template, I've just added them🙂

2023-08-24 03:40 UTC, Aibono1225 commented on src/pages/user-rules.js
> +    const newResNodesArr = [];
This is for getting the unique rule title and updating the rule list. The function is too complex, so I've split the logic into smaller functions in my new commit. 🙂

2023-08-24 05:57 UTC, Aibono1225 commented
![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/05a0938f-b1ef-4773-98b8-c5185d44e4f3)
**Figure: Updated button style**

2023-08-25 01:42 UTC, bradystroud requested changes

2023-08-25 01:42 UTC, bradystroud commented on src/pages/user-rules.js
> +          first: 30
Hardcoded values in queries and URLs (e.g., first: 30, first: 20, and https://api.github.com/graphql) should be moved to constants

2023-08-25 02:00 UTC, bradystroud approved these changes

2023-08-25 02:42 UTC, merged