Add community contribution UI elements
SSWConsulting/SSW.Rules pull request #118
Opened 2020-12-14 04:05 UTC by bradystroud

2020-12-15 23:55 UTC, AndreasLengkeek requested changes

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/components/header/header.js
> +            </Auth0Provider>
Move this provider to wrap the whole app in the Layout.js file

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/components/header/header.js
> +              redirectUri={process.env.CALLBACK}
Make sure these variables are in the template file

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/components/header/header.js
> +              redirectUri={process.env.CALLBACK}
I would use window.origin.location to get the current environments domain

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/templates/rule.js
> -                <small className="suggestion">
Leave this outside the React element

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/components/reaction/reaction.js
> +  var isLoggedIn = true;
if you import `auth0-react` class you can use the loggedIn flag
```const { loggedIn } = useAuth0();```

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/components/signin/signin.js
> +            logout({ returnTo: 'http://localhost:3000' });
needs to be generic as this needs to work on multiple environments

2020-12-15 23:55 UTC, AndreasLengkeek commented on src/components/signin/signin.js
> +  user && console.log(user);
remove console logs in production code

2020-12-16 01:17 UTC, bradystroud commented on src/templates/rule.js
> +                    onClick={() => setLikesCount(likesCount + 1)}
I am not actually incrementing `likesCount`. I am updating the state of `likesCount` to one more than the current state. I followed these docs to add this [https://reactjs.org/docs/hooks-state.html](https://reactjs.org/docs/hooks-state.html)

2020-12-16 05:49 UTC, AndreasLengkeek approved these changes

2020-12-16 05:50 UTC, merged