Added Megamenu v4
SSWConsulting/SSW.Rules pull request #1192
Opened 2024-01-02 07:30 UTC by Harry-Ross

Relates to #1188 

* Adds the new megamenu, published from NPM

2024-01-03 07:46 UTC, Aibono1225 commented
Hey @Harry-Ross ,

It seems like the dropdown will be hidden by our new megamenu once we log in
         1. Please fix this UI issue

![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/257e185b-eb21-4964-9279-a51677911db4)

2024-01-03 23:44 UTC, JackDevAU requested changes
Looks good! 

1. Please action @Aibono1225 comment

2024-01-04 09:12 UTC, Aibono1225 commented
> 1. Please action @Aibono1225 comment

Done - Updated the style 🙂:
![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/9bdbcdf6-2fe2-49d8-a6ea-ac0f473ec3c6)

2024-01-04 23:49 UTC, JackDevAU approved these changes

2024-01-05 01:25 UTC, merged