Issue 799
SSWConsulting/SSW.Rules pull request #802
Opened 2022-01-06 04:08 UTC by brydeno

Implemented a scan for orphaned rules and categories with broken rules.

- [ ] Recommended extensions have been installed if using VS Code

Issue 799

Updated the build to scan for any orphaned rules and also any categories containing rules which don't exist.
The scan is currently only output to the console log. Once the identified problems are all fixed, this should then be updated to make the build fail.

2022-01-06 10:52 UTC, bradystroud requested changes

2022-01-06 10:52 UTC, bradystroud commented on gatsby-node.js
> +  //  var count = 0;
Can we remove these comments?

2022-02-24 04:44 UTC, bradystroud approved these changes

2022-02-24 05:02 UTC, christianmorfordwaitessw commented on gatsby-node.js
> +  //  var count = 0;
**Done** - Commented code removed

2022-02-24 05:02 UTC, merged