✨ 800 - Add collapsable rule sidebar
SSWConsulting/SSW.Rules pull request #990
Opened 2023-05-29 10:09 UTC by Aibono1225

Fixes https://github.com/SSWConsulting/SSW.Rules/issues/800

Changes I made:
- Added new sidebar to single rule view.
- Added Authors + Categories + Related Rules to the new sidebar
- Removed Authors + Categories + Related Rules from bottom section
- Make the sidebar responsive and sticky
- Added button to collapse the sidebar

Link of done video: https://youtu.be/wrXbO_0MI0Y

![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/587eaedc-5106-4998-9ec9-79f2d5d53310)

![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/8dd66f12-0dcc-4e66-82b3-93af04ac86b1)

2023-05-29 23:41 UTC, bradystroud requested changes

2023-05-29 23:41 UTC, bradystroud commented on src/images/clock-regular.svg
I think we can use FontAwesome for this icon

2023-05-29 23:41 UTC, bradystroud commented on src/components/categories/categories.js
This filename could be a little more descriptive e.g. `sidebar-categories`

2023-05-30 01:54 UTC, jaydenalchin requested changes
Fantastic work and nice done video! Please see my feedback below: 

1. Content in the sidebar should be downsized slightly for better scalability. E.g. text-sm, w-12 h-12 on author bubbles.
2. Separate the sidebar sections with a little more space between for readability. 
3. The bookmark / edit / github icons should have more space between them for clickability.
4. The 'Ratings' section needs to be updated with more spacing & center alignment to compensate for the other sections moving into the sidebar - see mockup below

![image](https://github.com/SSWConsulting/SSW.Rules/assets/75593567/6c1cee71-663e-4701-af2e-f14347dfd4d8)
**Figure: Ratings section**

2023-06-02 01:40 UTC, jaydenalchin commented
> Done ⭐ See below:
@Aibono1225 That ratings section is looking good! 

1. Can you please show the rule title & icons as well? 

I also think we should reevaluate the need for collapse/expand interaction you showed in the demo video. I feel it's adding clutter to the UI without providing much actual value. Would love to hear thoughts from @bradystroud @tiagov8

2023-06-02 04:08 UTC, Aibono1225 commented
> > Done ⭐ See below:
> > @Aibono1225 That ratings section is looking good!
> 
> 1. Can you please show the rule title & icons as well?

Done - here the screenshots:
<img width="382" alt="destop" src="https://github.com/SSWConsulting/SSW.Rules/assets/127192800/72e1bb3a-88d7-4ba8-bd94-bf6aa54e9243">
**Desktop View**

<img width="244" alt="mobile" src="https://github.com/SSWConsulting/SSW.Rules/assets/127192800/14f84344-0972-4d75-8ec3-cdd24be61a60">
**Mobile View**



The rating section is also responsive:
![772F1F38-F998-46A8-8CE7-AD18897B52AB](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/2134935e-0ed5-4737-9b8b-1500094ba9ac)

2023-06-09 03:10 UTC, Aibono1225 commented
As per Tiago's emails, the following changes have been made:

1. These old icons have been added back:  bookmark, edit(Netlify), and edit(GitHub) and 'see history' icon
2. The authors' section will now only display photos.
3. The authors'section and categories section now have 'info' links that show "how to add an author/category"
4. The related rules are no longer numbered.

Here is the new Done Videor: https://youtu.be/1ort1enSMLo

![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/beeb552e-76fb-42be-b15e-83186f5ee520)
**Desktop View**


![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/f90e2494-5e1a-4a1a-8b2b-8c8ab32617f6)
**Mobile View**

2023-06-12 22:39 UTC, tiagov8 commented
LGTM ✅

Thanks @Aibono1225 and @jaydenalchin for applying less is more ;)

2023-06-12 22:54 UTC, jaydenalchin commented
Excellent work @Aibono1225 LGTM and thanks I know that was a lot of feedback to go through! ✨💖

I have one last suggestion that is not need-to-have but nice-to-have if @bradystroud or @tiagov8 agree:

1. For a nice subtle indication that there's overflow content, we could add a small fade-out effect on the top and bottom of the scrolling sidebar like this: https://pqina.nl/blog/fade-out-overflow-using-css-mask-image/

2023-06-13 03:10 UTC, Aibono1225 commented
Thank you @jaydenalchin . The link you provided was very helpful, and the new CSS effect looks so cool to me! 😊

I have added the fade-out effect to the sidebar, as you can see below:
![image](https://github.com/SSWConsulting/SSW.Rules/assets/127192800/3e6db5ef-eb3c-4c41-95d2-e1b7d4373fe2)

2023-06-13 05:21 UTC, jaydenalchin approved these changes
Awesome work love this big update! 🎉🚀

2023-06-13 05:23 UTC, bradystroud requested changes

2023-06-13 05:23 UTC, bradystroud commented on src/style.css
> +    /* grid-template-columns: auto 2rem 0.5rem 1rem 2.2rem 0.5rem 1rem 2.2rem 0.5rem 1rem 2.3rem 1rem auto; */
can we remove this?

2023-06-13 05:36 UTC, Aibono1225 commented on src/style.css
> +    /* grid-template-columns: auto 2rem 0.5rem 1rem 2.2rem 0.5rem 1rem 2.2rem 0.5rem 1rem 2.3rem 1rem auto; */
Done (●'◡'●)

2023-06-14 01:33 UTC, bradystroud approved these changes

2023-06-14 01:34 UTC, merged